### ISSUE TITLE
X Version of bot doesn't reply anymore

### ISSUE THREAD

**Issue by NickTheWilder** [yeenbean/pauljac3-mastodon-bot#10]
Just recently started following the bot on Twitter again after a hiatus of the social media.

I noticed the bot doesn't reply anymore. Is that by design? 

Could be related to the API changes?

https://x.com/0fryx/status/1721165579845878119?s=46&t=GBgZO0JcuZEE26HiwAyGJQ

**Comment by yeenbean** [comment]
This is related to the cost of the X API. If I were to implement the reply feature on the free tier, the bot would function for about a week, then would cease to work until the next API billing cycle. Unless enough people were willing to donate the cost, I would not feel inclined to pay for the API--especially with the current ownership of the platform. I know this is disappointing to hear, but I'm just one guy with a low income. Sorry. :(

For what it's worth, the reply feature *does* work and is already implemented for ActivityPub and ATProto platforms. If X decides to cater its API costs for individual developers, I will reconsider implementing replies for X.

**Comment by NickTheWilder** [comment]
Unfortunate, but I had a feeling that was the reason. No worries, thanks!
